# spring
spring:
  profiles:
    active: dev # 指定活动的profile：dev表示开发环境；prod表示生产环境
  application:
    name: core-test-web # 应用名称
  web:
    locale: zh_CN # 设置国际化默认语言环境
    locale-resolver: fixed # 使用固定区域设置
  messages:
    encoding: UTF-8 # 设置消息编码
  servlet:
    multipart:
      enabled: true # 是否开启文件上传支持，默认为true
      max-file-size: 2MB # 指定文件大小最大值，默认1MB
      max-request-size: 10MB # 指定每次请求的最大值，默认为10MB
      file-size-threshold: 1MB # 设定文件写入磁盘的阈值，单位为MB或KB，默认为0

# server
server:
  servlet:
    encoding:
      enabled: true # 是否开启http的编码支持，默认为true
      charset: UTF-8 # 指定http请求和相应的Charset，默认:UTF-8
      force: true # 是否强制对http请求和响应进行编码，默认为true
